media:
  input: src/media
  output: /media
content:
  - name: "settings"
    label: "Basic Settings"
    type: "file"
    path: "src/data/settings.json"
    fields:
      - { name: "name", label: "Name", type: "string", required: true }
      - { name: "email", label: "Email Address", type: "string", required: true }
      - { name: "phone", label: "Phone Number", type: "string", required: true }
      - { name: "address", label: "Address", type: "string", required: true }
      - { name: "title", label: "Title of Website", type: "string", required: true }
      - { name: "description", label: "Description of Website", type: "string", required: true }
      - { name: "url", label: "URL", type: "string", required: true }
      - { name: "keywords", label: "Keywords", type: "string",}
      - { name: "image", label: "OG:Image", type: "image",}
  - name: "social"
    label: "Social Media"
    type: "file"
    path: "src/data/social.json"
    fields:
      - { name: "facebook", label: "Facebook", type: "string",}
      - { name: "twitter", label: "Twitter", type: "string",}
      - { name: "instagram", label: "Instagram", type: "string",}
      - { name: "linkedin", label: "LinkedIn", type: "string",}
      - { name: "youtube", label: "Youtube", type: "string",}  
  - name: "team"
    label: "Team Members"
    type: "file"
    path: "src/data/team.json"
    fields:
      - { name: "id", label: "ID", type: "string", required: true }
      - { name: "name", label: "Name", type: "string", required: true }
      - { name: "role", label: "Role", type: "string", required: true }
      - { name: "image", label: "Image", type: "image", required: true }
      - { name: "imageAlt", label: "Image Alt Text", type: "string", required: true }
      - { name: "description", label: "Description", type: "string", required: true }
